branches:
   - main
   - name: dev
     prerelease: true
     channel: dev


plugins:
   - - "@semantic-release/commit-analyzer"
     - preset: conventionalcommits
       releaseRules:
         - type: feat
           breaking: false
           release: minor
         - type: feat
           breaking: true
           release: major
         - type: chore
           breaking: false
           release: patch
         - type: chore
           breaking: true
           release: major
         - type: refactor
           breaking: false
           release: patch
         - type: refactor
           breaking: true
           release: major

   - "@semantic-release/release-notes-generator"
   - "@semantic-release/changelog"
   - "@semantic-release/npm"
   - "@semantic-release/github"
   - - "@semantic-release/git"
     - message: "chore(release): ${nextRelease.version} [skip ci]"
       assets:
        - package.json
        - CHANGELOG.md
